"""create stock_batches table

Revision ID: 424fb603f21f
Revises: 7f31b262c46d
Create Date: 2026-03-17 12:17:45.337034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '424fb603f21f'
down_revision: Union[str, Sequence[str], None] = '7f31b262c46d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('entry_quantity', sa.Integer(), nullable=False),
    sa.Column('current_quantity', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('estimated_unit_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_batches_id'), 'stock_batches', ['id'], unique=False)
    op.create_index(op.f('ix_stock_batches_item_id'), 'stock_batches', ['item_id'], unique=False)
    op.create_index(op.f('ix_stock_batches_source_type'), 'stock_batches', ['source_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_batches_source_type'), table_name='stock_batches')
    op.drop_index(op.f('ix_stock_batches_item_id'), table_name='stock_batches')
    op.drop_index(op.f('ix_stock_batches_id'), table_name='stock_batches')
    op.drop_table('stock_batches')
    # ### end Alembic commands ###
