"""create social_assessments table

Revision ID: 4b67dbcbad52
Revises: 654fd6cb306f
Create Date: 2026-03-17 11:16:32.177530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b67dbcbad52'
down_revision: Union[str, Sequence[str], None] = '654fd6cb306f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('assessment_date', sa.Date(), nullable=False),
    sa.Column('monthly_income_total_at_time', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('income_per_capita_at_time', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('vulnerability_score', sa.Integer(), nullable=False),
    sa.Column('system_suggestion', sa.String(length=30), nullable=False),
    sa.Column('final_decision', sa.String(length=30), nullable=False),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('exception_reason', sa.Text(), nullable=True),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=False),
    sa.Column('co_approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('next_revaluation_date', sa.Date(), nullable=True),
    sa.Column('technical_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['co_approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_assessments_family_id'), 'social_assessments', ['family_id'], unique=False)
    op.create_index(op.f('ix_social_assessments_id'), 'social_assessments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_social_assessments_id'), table_name='social_assessments')
    op.drop_index(op.f('ix_social_assessments_family_id'), table_name='social_assessments')
    op.drop_table('social_assessments')
    # ### end Alembic commands ###
