"""add social profile fields to families

Revision ID: 5ddbb2c2cb3c
Revises: 94e482055b71
Create Date: 2026-03-19 17:42:57.562583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5ddbb2c2cb3c'
down_revision: Union[str, Sequence[str], None] = '94e482055b71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('families', sa.Column('attends_church', sa.Boolean(), nullable=False))
    op.add_column('families', sa.Column('church_name', sa.String(length=150), nullable=True))
    op.add_column('families', sa.Column('community_relationship', sa.String(length=50), nullable=True))
    op.add_column('families', sa.Column('responsible_education_level', sa.String(length=80), nullable=True))
    op.add_column('families', sa.Column('has_internet_access', sa.Boolean(), nullable=False))
    op.add_column('families', sa.Column('has_mobile_phone', sa.Boolean(), nullable=False))
    op.add_column('families', sa.Column('has_computer', sa.Boolean(), nullable=False))
    op.alter_column('families', 'housing_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('families', 'zip_code',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('families', 'street',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.alter_column('families', 'complement',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               type_=sa.String(length=120),
               existing_nullable=True)
    op.alter_column('families', 'neighborhood',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.alter_column('families', 'city',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.alter_column('families', 'updated_by_user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_families_neighborhood'), table_name='families')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_families_neighborhood'), 'families', ['neighborhood'], unique=False)
    op.alter_column('families', 'updated_by_user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('families', 'city',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               existing_nullable=False)
    op.alter_column('families', 'neighborhood',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               existing_nullable=False)
    op.alter_column('families', 'complement',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               existing_nullable=True)
    op.alter_column('families', 'street',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150),
               existing_nullable=False)
    op.alter_column('families', 'zip_code',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               existing_nullable=True)
    op.alter_column('families', 'housing_type',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30),
               existing_nullable=True)
    op.drop_column('families', 'has_computer')
    op.drop_column('families', 'has_mobile_phone')
    op.drop_column('families', 'has_internet_access')
    op.drop_column('families', 'responsible_education_level')
    op.drop_column('families', 'community_relationship')
    op.drop_column('families', 'church_name')
    op.drop_column('families', 'attends_church')
    # ### end Alembic commands ###
