"""create benefits table

Revision ID: 654fd6cb306f
Revises: ff9e45d3bd53
Create Date: 2026-03-17 10:01:45.143035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '654fd6cb306f'
down_revision: Union[str, Sequence[str], None] = 'ff9e45d3bd53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benefits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('benefit_type', sa.String(length=50), nullable=False),
    sa.Column('monthly_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('counts_as_income', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_benefits_benefit_type'), 'benefits', ['benefit_type'], unique=False)
    op.create_index(op.f('ix_benefits_family_id'), 'benefits', ['family_id'], unique=False)
    op.create_index(op.f('ix_benefits_id'), 'benefits', ['id'], unique=False)
    op.create_index(op.f('ix_benefits_person_id'), 'benefits', ['person_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_benefits_person_id'), table_name='benefits')
    op.drop_index(op.f('ix_benefits_id'), table_name='benefits')
    op.drop_index(op.f('ix_benefits_family_id'), table_name='benefits')
    op.drop_index(op.f('ix_benefits_benefit_type'), table_name='benefits')
    op.drop_table('benefits')
    # ### end Alembic commands ###
