"""create basket_types and basket_type_items tables

Revision ID: 6aa89ffd7377
Revises: 16d7d602fc6d
Create Date: 2026-03-17 14:53:48.254216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aa89ffd7377'
down_revision: Union[str, Sequence[str], None] = '16d7d602fc6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('basket_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_basket_types_id'), 'basket_types', ['id'], unique=False)
    op.create_index(op.f('ix_basket_types_name'), 'basket_types', ['name'], unique=True)
    op.create_table('basket_type_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('basket_type_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('required_quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['basket_type_id'], ['basket_types.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('basket_type_id', 'item_id', name='uq_basket_type_items_basket_type_id_item_id')
    )
    op.create_index(op.f('ix_basket_type_items_basket_type_id'), 'basket_type_items', ['basket_type_id'], unique=False)
    op.create_index(op.f('ix_basket_type_items_id'), 'basket_type_items', ['id'], unique=False)
    op.create_index(op.f('ix_basket_type_items_item_id'), 'basket_type_items', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_basket_type_items_item_id'), table_name='basket_type_items')
    op.drop_index(op.f('ix_basket_type_items_id'), table_name='basket_type_items')
    op.drop_index(op.f('ix_basket_type_items_basket_type_id'), table_name='basket_type_items')
    op.drop_table('basket_type_items')
    op.drop_index(op.f('ix_basket_types_name'), table_name='basket_types')
    op.drop_index(op.f('ix_basket_types_id'), table_name='basket_types')
    op.drop_table('basket_types')
    # ### end Alembic commands ###
