"""create families and family_contacts

Revision ID: 8656ab657130
Revises: 076fabe21d3b
Create Date: 2026-03-16 14:14:59.367626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8656ab657130'
down_revision: Union[str, Sequence[str], None] = '076fabe21d3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('families',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('internal_code', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('registration_date', sa.Date(), nullable=False),
    sa.Column('last_evaluation_date', sa.Date(), nullable=True),
    sa.Column('next_revaluation_date', sa.Date(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('monthly_income_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('monthly_essential_expenses', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('income_per_capita', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('receives_government_assistance', sa.Boolean(), nullable=False),
    sa.Column('housing_type', sa.String(length=30), nullable=True),
    sa.Column('has_water_supply', sa.Boolean(), nullable=False),
    sa.Column('has_electricity', sa.Boolean(), nullable=False),
    sa.Column('has_sanitation', sa.Boolean(), nullable=False),
    sa.Column('rooms_count', sa.Integer(), nullable=False),
    sa.Column('bedrooms_count', sa.Integer(), nullable=False),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('street', sa.String(length=150), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('complement', sa.String(length=100), nullable=True),
    sa.Column('neighborhood', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('reference_point', sa.String(length=255), nullable=True),
    sa.Column('total_residents', sa.Integer(), nullable=False),
    sa.Column('total_adults', sa.Integer(), nullable=False),
    sa.Column('total_children', sa.Integer(), nullable=False),
    sa.Column('total_elderly', sa.Integer(), nullable=False),
    sa.Column('total_babies', sa.Integer(), nullable=False),
    sa.Column('has_pregnant_member', sa.Boolean(), nullable=False),
    sa.Column('has_disabled_member', sa.Boolean(), nullable=False),
    sa.Column('has_chronic_illness_member', sa.Boolean(), nullable=False),
    sa.Column('has_unemployed_member', sa.Boolean(), nullable=False),
    sa.Column('needs_extra_support', sa.Boolean(), nullable=False),
    sa.Column('social_notes', sa.Text(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_families_id'), 'families', ['id'], unique=False)
    op.create_index(op.f('ix_families_internal_code'), 'families', ['internal_code'], unique=True)
    op.create_index(op.f('ix_families_neighborhood'), 'families', ['neighborhood'], unique=False)
    op.create_index(op.f('ix_families_status'), 'families', ['status'], unique=False)
    op.create_table('family_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('contact_name', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('contact_type', sa.String(length=30), nullable=False),
    sa.Column('is_whatsapp', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_contacts_family_id'), 'family_contacts', ['family_id'], unique=False)
    op.create_index(op.f('ix_family_contacts_id'), 'family_contacts', ['id'], unique=False)
    op.create_index(op.f('ix_family_contacts_phone'), 'family_contacts', ['phone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_family_contacts_phone'), table_name='family_contacts')
    op.drop_index(op.f('ix_family_contacts_id'), table_name='family_contacts')
    op.drop_index(op.f('ix_family_contacts_family_id'), table_name='family_contacts')
    op.drop_table('family_contacts')
    op.drop_index(op.f('ix_families_status'), table_name='families')
    op.drop_index(op.f('ix_families_neighborhood'), table_name='families')
    op.drop_index(op.f('ix_families_internal_code'), table_name='families')
    op.drop_index(op.f('ix_families_id'), table_name='families')
    op.drop_table('families')
    # ### end Alembic commands ###
