"""create delivery_schedules and deliveries tables

Revision ID: 94e482055b71
Revises: 6aa89ffd7377
Create Date: 2026-03-17 15:39:21.810731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94e482055b71'
down_revision: Union[str, Sequence[str], None] = '6aa89ffd7377'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('basket_type_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['basket_type_id'], ['basket_types.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_schedules_basket_type_id'), 'delivery_schedules', ['basket_type_id'], unique=False)
    op.create_index(op.f('ix_delivery_schedules_family_id'), 'delivery_schedules', ['family_id'], unique=False)
    op.create_index(op.f('ix_delivery_schedules_id'), 'delivery_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_delivery_schedules_status'), 'delivery_schedules', ['status'], unique=False)
    op.create_table('deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_schedule_id', sa.Integer(), nullable=True),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('basket_type_id', sa.Integer(), nullable=False),
    sa.Column('delivery_date', sa.DateTime(), nullable=False),
    sa.Column('delivered_by_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['basket_type_id'], ['basket_types.id'], ),
    sa.ForeignKeyConstraint(['delivered_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['delivery_schedule_id'], ['delivery_schedules.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deliveries_basket_type_id'), 'deliveries', ['basket_type_id'], unique=False)
    op.create_index(op.f('ix_deliveries_delivery_schedule_id'), 'deliveries', ['delivery_schedule_id'], unique=False)
    op.create_index(op.f('ix_deliveries_family_id'), 'deliveries', ['family_id'], unique=False)
    op.create_index(op.f('ix_deliveries_id'), 'deliveries', ['id'], unique=False)
    op.create_index(op.f('ix_deliveries_status'), 'deliveries', ['status'], unique=False)
    op.add_column('stock_movements', sa.Column('delivery_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_stock_movements_delivery_id'), 'stock_movements', ['delivery_id'], unique=False)
    op.create_foreign_key(None, 'stock_movements', 'deliveries', ['delivery_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock_movements', type_='foreignkey')
    op.drop_index(op.f('ix_stock_movements_delivery_id'), table_name='stock_movements')
    op.drop_column('stock_movements', 'delivery_id')
    op.drop_index(op.f('ix_deliveries_status'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_id'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_family_id'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_delivery_schedule_id'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_basket_type_id'), table_name='deliveries')
    op.drop_table('deliveries')
    op.drop_index(op.f('ix_delivery_schedules_status'), table_name='delivery_schedules')
    op.drop_index(op.f('ix_delivery_schedules_id'), table_name='delivery_schedules')
    op.drop_index(op.f('ix_delivery_schedules_family_id'), table_name='delivery_schedules')
    op.drop_index(op.f('ix_delivery_schedules_basket_type_id'), table_name='delivery_schedules')
    op.drop_table('delivery_schedules')
    # ### end Alembic commands ###
