"""create people table

Revision ID: ff9e45d3bd53
Revises: 8656ab657130
Create Date: 2026-03-16 14:52:44.814405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff9e45d3bd53'
down_revision: Union[str, Sequence[str], None] = '8656ab657130'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('kinship', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('education_level', sa.String(length=50), nullable=True),
    sa.Column('is_currently_studying', sa.Boolean(), nullable=False),
    sa.Column('is_currently_working', sa.Boolean(), nullable=False),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('individual_income', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('has_disability', sa.Boolean(), nullable=False),
    sa.Column('has_chronic_illness', sa.Boolean(), nullable=False),
    sa.Column('is_pregnant', sa.Boolean(), nullable=False),
    sa.Column('is_nursing_mother', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_family_responsible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_people_family_id'), 'people', ['family_id'], unique=False)
    op.create_index(op.f('ix_people_full_name'), 'people', ['full_name'], unique=False)
    op.create_index(op.f('ix_people_id'), 'people', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_people_id'), table_name='people')
    op.drop_index(op.f('ix_people_full_name'), table_name='people')
    op.drop_index(op.f('ix_people_family_id'), table_name='people')
    op.drop_table('people')
    # ### end Alembic commands ###
